Testes JMeter new workflow

diff --git a/.github/workflows/teste_old_worfkflow.yml b/.github/workflows/teste_old_worfkflow.yml
--- a/.github/workflows/teste_old_worfkflow.yml
+++ b/.github/workflows/teste_old_worfkflow.yml
@@ -67,40 +67,96 @@ jobs:
           wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
           tar -xzf apache-jmeter-5.6.2.tgz
 
-      - name: JMETER - testes simples (Execução + Relatório Separado)
-        run: |
-          echo "1. Limpando relatórios antigos..."
-          rm -rf jmeter-teastore/results-simples.jtl jmeter-teastore/report-simples
+      # - name: JMETER - testes simples (Execução + Relatório Separado)
+      #   run: |
+      #     echo "1. Limpando relatórios antigos..."
+      #     rm -rf jmeter-teastore/results-simples.jtl jmeter-teastore/report-simples
 
-          echo "2. Executando teste simples (Gerando apenas JTL)..."
-          # Removemos o -e -o daqui para evitar falha na geração se houver erro no teste
-          ./apache-jmeter-5.6.2/bin/jmeter -n \
-            -t jmeter-teastore/teste-carga-simples.jmx \
-            -l jmeter-teastore/results-simples.jtl \
-            -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros (isso é esperado em testes de carga)"
+      #     echo "2. Executando teste simples (Gerando apenas JTL)..."
+      #     # Removemos o -e -o daqui para evitar falha na geração se houver erro no teste
+      #     ./apache-jmeter-5.6.2/bin/jmeter -n \
+      #       -t jmeter-teastore/teste-carga-simples.jmx \
+      #       -l jmeter-teastore/results-simples.jtl \
+      #       -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros (isso é esperado em testes de carga)"
           
-          echo "3. Gerando Relatório HTML a partir do JTL..."
-          if [ -s jmeter-teastore/results-simples.jtl ]; then
-             ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-simples.jtl -o jmeter-teastore/report-simples
-             echo "✅ Relatório simples gerado!"
-          else
-             echo "❌ Arquivo JTL vazio ou não existe. O teste falhou drasticamente."
-          fi
+      #     echo "3. Gerando Relatório HTML a partir do JTL..."
+      #     if [ -s jmeter-teastore/results-simples.jtl ]; then
+      #        ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-simples.jtl -o jmeter-teastore/report-simples
+      #        echo "✅ Relatório simples gerado!"
+      #     else
+      #        echo "❌ Arquivo JTL vazio ou não existe. O teste falhou drasticamente."
+      #     fi
 
-      - name: JMETER - Testes complexos (Execução + Relatório Separado)
+      # - name: JMETER - Testes complexos (Execução + Relatório Separado)
+      #   run: |
+      #     echo "1. Limpando relatórios antigos..."
+      #     rm -rf jmeter-teastore/results-complexos.jtl jmeter-teastore/report-complexos
+
+      #     echo "2. Executando teste complexo (Gerando apenas JTL)..."
+      #     ./apache-jmeter-5.6.2/bin/jmeter -n \
+      #       -t jmeter-teastore/cenarios-complexos.jmx \
+      #       -l jmeter-teastore/results-complexos.jtl \
+      #       -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros"
+          
+      #     echo "3. Gerando Relatório HTML a partir do JTL..."
+      #     if [ -s jmeter-teastore/results-complexos.jtl ]; then
+      #        ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-complexos.jtl -o jmeter-teastore/report-complexos
+      #        echo "✅ Relatório complexo gerado!"
+      #     else
+      #        echo "❌ Arquivo JTL vazio ou não existe."
+          
+      - name: JMETER - Testes 100VUS
         run: |
           echo "1. Limpando relatórios antigos..."
-          rm -rf jmeter-teastore/results-complexos.jtl jmeter-teastore/report-complexos
+          rm -rf jmeter-teastore/results-100-vus.jtl jmeter-teastore/report-100-vus
 
           echo "2. Executando teste complexo (Gerando apenas JTL)..."
           ./apache-jmeter-5.6.2/bin/jmeter -n \
-            -t jmeter-teastore/cenarios-complexos.jmx \
-            -l jmeter-teastore/results-complexos.jtl \
+            -t jmeter-teastore/cenario-100-vus.jmx \
+            -l jmeter-teastore/results-100-vus.jtl \
             -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros"
           
           echo "3. Gerando Relatório HTML a partir do JTL..."
-          if [ -s jmeter-teastore/results-complexos.jtl ]; then
-             ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-complexos.jtl -o jmeter-teastore/report-complexos
+          if [ -s jmeter-teastore/results-100-vus.jtl ]; then
+             ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-100-vus.jtl -o jmeter-teastore/report-100-vus
+             echo "✅ Relatório complexo gerado!"
+          else
+             echo "❌ Arquivo JTL vazio ou não existe."
+          fi
+      
+      - name: JMETER - Testes 100VUS
+        run: |
+          echo "1. Limpando relatórios antigos..."
+          rm -rf jmeter-teastore/results-500-vus.jtl jmeter-teastore/report-500-vus
+
+          echo "2. Executando teste complexo (Gerando apenas JTL)..."
+          ./apache-jmeter-5.6.2/bin/jmeter -n \
+            -t jmeter-teastore/cenario-500-vus.jmx \
+            -l jmeter-teastore/results-500-vus.jtl \
+            -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros"
+          
+          echo "3. Gerando Relatório HTML a partir do JTL..."
+          if [ -s jmeter-teastore/results-500-vus.jtl ]; then
+             ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-500-vus.jtl -o jmeter-teastore/report-500-vus
+             echo "✅ Relatório complexo gerado!"
+          else
+             echo "❌ Arquivo JTL vazio ou não existe."
+          fi
+        
+      - name: JMETER - Testes 100VUS
+        run: |
+          echo "1. Limpando relatórios antigos..."
+          rm -rf jmeter-teastore/results-1000-vus.jtl jmeter-teastore/report-1000-vus
+
+          echo "2. Executando teste complexo (Gerando apenas JTL)..."
+          ./apache-jmeter-5.6.2/bin/jmeter -n \
+            -t jmeter-teastore/cenario-1000-vus.jmx \
+            -l jmeter-teastore/results-1000-vus.jtl \
+            -Jhostname=${HOSTNAME} -Jport=${PORT} || echo "⚠️ JMeter executou com erros"
+          
+          echo "3. Gerando Relatório HTML a partir do JTL..."
+          if [ -s jmeter-teastore/results-1000-vus.jtl ]; then
+             ./apache-jmeter-5.6.2/bin/jmeter -g jmeter-teastore/results-1000-vus.jtl -o jmeter-teastore/report-1000-vus
              echo "✅ Relatório complexo gerado!"
           else
              echo "❌ Arquivo JTL vazio ou não existe."
@@ -123,53 +179,58 @@ jobs:
           path: |
             jmeter-teastore/report-simples/
             jmeter-teastore/report-complexos/
+            jmeter-teastore/report-100-vus/
+            jmeter-teastore/report-500-vus/
+            jmeter-teastore/report-1000-vus/
             jmeter-teastore/results-simples.jtl
             jmeter-teastore/results-complexos.jtl
+            jmeter-teastore/results-1000-vus.jtl
+            jmeter-teastore/results-500-vus.jtl
             jmeter.log
 
       # ---------------------------- K 6 ----------------------------
-      - name: Install K6
-        run: |
-          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
-          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
-          sudo apt-get update
-          sudo apt-get install -y k6
+      # - name: Install K6
+      #   run: |
+      #     curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
+      #     echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
+      #     sudo apt-get update
+      #     sudo apt-get install -y k6
 
-      - name: K6 - testes simples
-        run: |
-          k6 run k6-teastore/teste-carga-simples.js \
-            --summary-export=k6-simple.json || true
+      # - name: K6 - testes simples
+      #   run: |
+      #     k6 run k6-teastore/teste-carga-simples.js \
+      #       --summary-export=k6-simple.json || true
 
-      - name: K6 - testes complexos
-        run: |
-          k6 run k6-teastore/cenarios-complexos.js \
-            --summary-export=k6-complex.json || true
+      # - name: K6 - testes complexos
+      #   run: |
+      #     k6 run k6-teastore/cenarios-complexos.js \
+      #       --summary-export=k6-complex.json || true
 
-      - name: Upload K6 summaries
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: relatorios-k6
-          path: |
-            k6-simple.json
-            k6-complex.json
+      # - name: Upload K6 summaries
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: relatorios-k6
+      #     path: |
+      #       k6-simple.json
+      #       k6-complex.json
 
       # -------------------------- L O C U S T ------------------------
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
+      # - name: Setup Python
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version: '3.11'
 
-      - name: Install Python dependencies
-        run: |
-          pip install -r requirements.txt
+      # - name: Install Python dependencies
+      #   run: |
+      #     pip install -r requirements.txt
 
-      - name: Locust - teste simples
-        run: |
-          locust -f locust-teastore/locustfile.py \
-            --headless -u 5 -r 2 -t 15s \
-            --host ${HOST}:${PORT}${BASE_PATH} \
-            --html locust-teastore/simple.html || true
+      # - name: Locust - teste simples
+      #   run: |
+      #     locust -f locust-teastore/locustfile.py \
+      #       --headless -u 5 -r 2 -t 15s \
+      #       --host ${HOST}:${PORT}${BASE_PATH} \
+      #       --html locust-teastore/simple.html || true
 
       # - name: Locust - teste complexo
       #   run: |
@@ -199,23 +260,23 @@ jobs:
       #       --host ${HOST}:${PORT}${BASE_PATH} \
       #       --html locust-teastore/report-1000-vus.html || true
 
-      - name: Upload Locust reports
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: relatorios-locust
-          path: locust-teastore/*.html
+      # - name: Upload Locust reports
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: relatorios-locust
+      #     path: locust-teastore/*.html
 
-      - name: Upload debug artifacts
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: debug-artifacts
-          path: |
-            jmeter-teastore/failures/**
-            jmeter-teastore/failures.jtl
-            logs/**
-            summary-unified.json
+      # - name: Upload debug artifacts
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: debug-artifacts
+      #     path: |
+      #       jmeter-teastore/failures/**
+      #       jmeter-teastore/failures.jtl
+      #       logs/**
+      #       summary-unified.json
       
       # ------------------------------------------------------------
       # 4) ENCERRAR
